

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

	public static void main(String[] args) {

		/**
		pruebaDAO pb = new pruebaDAO();
		prueba pr = new prueba(1234, "Elkin blanco", 123);
		pb.AgregarDatos(pr);
		
		System.out.println(pb.busqueda());
		
		
		prueba[] pr = new prueba[4];

		pr[0] = new prueba(2332, "Rosa Melano", 2323);
		pr[1] = new prueba(243345, "Elvis Presli", 8766);

		for (prueba e : pr) {
			pb.save(e);
		}

		pb.close();
		System.exit(0);
**/
	}
}
